---
- hosts: ibmi
  gather_facts: no
  collections:
   - ibm.power_ibmi

  vars:
    var1: "{{ active_jobs }} "

  tasks: 
  - name: Display all the active subsystems in this system.
    ibm.power_ibmi.ibmi_display_subsystem:
      subsystem: QINTER
    register: job_info
    

  - debug:
      var: '{{ job_info.active_jobs |  select("match", "JOB_NAME") }}'
