---
- hosts: ibmi
  gather_facts: no
  collections:
   - ibm.power_ibmi

  tasks:
  - name: Return ibmi_facts
    ibm.power_ibmi.ibmi_facts:
    register: ibmi_facts

  - name: Display
    debug:
      var: ibmi_facts.group_ptf_info[0]


