# Copyright (c) IBM Corporation 2019, 2020
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)
---
- hosts: ibmi
  gather_facts: no
  collections:
   - ibm.power_ibmi
  
  tasks:
  - name: start host server service
    ibm.power_ibmi.ibmi_device_vary:
       device_list: ['TAPVRT01']
       status: '*ON'
       joblog: True