---
- name: List Power Virtual Server Cloud Images
  hosts: localhost
  collections:
   - ibm.cloudcollection
  vars:
    pi_cloud_instance_id: 913b30caa50a2e9148828182cd7a7074:fbc96013-55e0-4045-9f47-e6bf176d4f7b

  tasks:
    - ibm_pi_images_info:
        pi_cloud_instance_id: "{{ pi_cloud_instance_id }}"
      register: images_list

    - debug:
        var: images_list.resource.image_info |
             items2dict(key_name='name', value_name='id')
